pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t jumalcapgemini/example-webserver .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker kill test
      - docker rm test
      - docker create --name test jumalcapgemini/example-webserver
      - docker cp ./test.sh test:/test.sh
      - docker start test /test.sh
    
  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u jumalcapgemini -p $PASS
      - docker push jumalcapgemini/example-webserver

  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull jumalcapgemini/example-webserver
      - docker stack deploy -c ./docker-compose.yml example-webserver