pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t jumalcapgemini/example-webserver .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker create --name test jumalcapgemini/example-webserver
      - docker cp ./test.sh test:/test.sh
      - docker start test /test.sh