pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build 
         --label org.label-schema.vcs-ref=$DRONE_COMMIT_SHA
         --label build-number=$DRONE_BUILD_NUMBER
         --label build-date="$(date)"
         -t jumalcapgemini/example-webserver:$DRONE_COMMIT_SHA .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker kill test
      - docker rm test
      - docker create --name test jumalcapgemini/example-webserver:$DRONE_COMMIT_SHA
      - docker cp ./test.sh test:/test.sh
      - docker start test /test.sh
    
  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u jumalcapgemini -p $PASS
      - docker push jumalcapgemini/example-webserver:$DRONE_COMMIT_SHA

  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull jumalcapgemini/example-webserver:$DRONE_COMMIT_SHA
      - docker tag jumalcapgemini/example-webserver:$DRONE_COMMIT_SHA
               jumalcapgemini/example-webserver:production
      - docker tag jumalcapgemini/example-webserver:$DRONE_COMMIT_SHA
               jumalcapgemini/example-webserver:latest
      - docker stack deploy -c ./docker-compose.yml example-webserver